#+TITLE: Maven Command Line Wrapper

* Introduction
This is a copy of the [[http://www.gradle.org/docs/current/userguide/gradle_wrapper.html][Gradle wrapper]] ported for use with [[http://maven.apache.org][Apache Maven]].

The Maven Command Line Wrapper will auto-download and install Apache Maven from the Internet and then run your Maven goals.

This is fork of [[https://github.com/bdemers/maven-wrapper][bdemers' maven-wrapper]] in order to provide the Maven Wrapper as a Maven plugin, for more flexible reuse/integration.

For example if used to run

 : mvn clean install

Then you would now run (without a leading =./= for MS Windows)
 : ./mvnw clean install
	
A wrapper created with Maven 3.0.4 will request Maven 3.0.4 if it's not already installed on the user's machine.

Notes: You need a valid JDK at least 1.6. The plugin was tested with Maven 3.0.2 and above.

For a small practical integration example, checkout the [[https://github.com/rimerosolutions/maven-wrapper-example][Maven Command Line Wrapper Example]] project.

* Maven Goals and Usage

For the list of goals and a usage guide, please consult the [[https://github.com/rimerosolutions/maven-wrapper/wiki][wiki]].
	
** Generating the Maven wrapper
After integrating the wrapper in another Maven project, run the following command to generate the wrapper.

 : mvn wrapper:wrapper

The =mvnw= and =mwnw.bat= command wrappers are generated at the root of the project folder.
	
The =maven= folder is generated with the relevant jar and properties file in the project directory.

You can now start using either the =mvnw= or =mvnw.bat= commands on any project without an existing maven installation!
